name: stock_scraper
dependencies:
  - python=3.7
  - tqdm
  - beautifulsoup4
  - pandas
  - requests
  - more-itertools
  - keyring
  - conda-forge::bidict
  - conda-forge::typing_extensions
  - pip
  - pip:
    - pyppeteer
    - aioprocessing
