name: mlir
dependencies:
  - python=3.7
  - conda-forge::bazel
  - cmake>=3.13
  - clang
  - clangxx
  - jupyter
  - conda-forge::ninja
  - conda-forge::jupyter_http_over_ws
  - matplotlib
  - pip
  - pip:
    - tensorflow
