name: autograd

dependencies:
  - python=3.7
  - numpy
  - pytest
  - pytest-cov
  - more-itertools
  - conda-forge::typing_extensions
  - pip
  - pip:
    - forbiddenfruit

# Only required for examples
  - conda-forge::jupyterlab
  - pandas
  - tqdm