//===- PaulLangPasses.td - PaulLang dialect passes ---------*- tablegen -*-===//
//
// This file is licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

#ifndef PAULLANG_PASSES
#define PAULLANG_PASSES

include "PaulLangOps.td"

#endif // PAULLANG_PASSES
